# Generated by Django 5.1 on 2024-08-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_doctor_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='area_of_residence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specialization'),
        ),
    ]
