# Generated by Django 5.1 on 2024-08-23 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_doctor_area_of_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='doctor',
            name='area_of_residence',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
